/* layerCSpecies.js — the species each Layer C model can actually voice.
   ───────────────────────────────────────────────────────────────────────────
   The /generation page lets a user pick "voices" (Layer C events). Those chips
   must match whatever Layer C attempt is selected on /dev/settings — a model
   can only generate species it was built for.

   The species lists are NOT hand-maintained here. They come from
   `layerCSpeciesIndex.json`, a DERIVED artifact generated by
   `acoustic_ai/scripts/build_layer_c_species_index.py` from each attempt's
   source of truth:
     • burger__mvp_2__retrieval_v2_library → the v2 event-index CSV (63 species)
     • burger__mvp_3__sa3_generative_live  → registry.yaml `species_pools` (2)
   Rerun that script when the underlying data changes; never edit the JSON or
   these arrays by hand.

   The selected attempt id comes from GET /api/model-config → slots.layer_c.

   NOTE on the "safe" set: the only species BOTH models share are Horsfield's
   Bronze-cuckoo and Spotted Nightjar — so a prompt built from SAFE_SPECIES
   generates on either model. The /generation presets lean on this.            */

import speciesIndex from "./layerCSpeciesIndex.json";

const RETRIEVAL_ATTEMPT = "burger__mvp_2__retrieval_v2_library";
const SA3_ATTEMPT = "burger__mvp_3__sa3_generative_live";

function article(label) {
  return /^[aeiou]/i.test(label) ? "an" : "a";
}

// Attach the natural-language `phrase` composeSelections() drops into the
// prompt text (the JSON carries only key + label).
function withPhrases(list) {
  return (list || []).map(({ key, label }) => ({
    key,
    label,
    phrase: `${article(label)} ${label}`,
  }));
}

export const RETRIEVAL_V2_SPECIES = withPhrases(
  speciesIndex.attempts?.[RETRIEVAL_ATTEMPT]?.species,
);
export const SA3_LIVE_SPECIES = withPhrases(
  speciesIndex.attempts?.[SA3_ATTEMPT]?.species,
);

// Species both models can voice — the "safe choice" for presets that must work
// regardless of which Layer C attempt is selected (the SA3 set ⊆ retrieval set).
const retrievalKeys = new Set(RETRIEVAL_V2_SPECIES.map((s) => s.key));
export const SAFE_SPECIES = SA3_LIVE_SPECIES.filter((s) => retrievalKeys.has(s.key));

// attempt id → species list. Anything not listed (e.g. the boobook smoke
// attempt, or an unknown/absent selection) falls back to the broad retrieval
// library so the chip rail is never empty in the demo.
const SPECIES_BY_ATTEMPT = {
  [RETRIEVAL_ATTEMPT]: RETRIEVAL_V2_SPECIES,
  [SA3_ATTEMPT]: SA3_LIVE_SPECIES,
};

const FALLBACK_SPECIES = RETRIEVAL_V2_SPECIES;

/**
 * Resolve the species chip list for the currently-selected Layer C attempt.
 * @param {string} [attemptId] value of model-config slots.layer_c ("" = default)
 * @returns {Array<{key:string,label:string,phrase:string}>}
 */
export function speciesForLayerC(attemptId) {
  return SPECIES_BY_ATTEMPT[attemptId] || FALLBACK_SPECIES;
}
